name: Waypoints.Signs
version: 1.2.1
main: waypoints.signs.WpsSignPlugin
commands:
  wpssigns:
    description: root command
    usage: /<command> [subcommand] [args]
  waypointssigns:
    description: root command
    usage: /<command> [subcommand] [args]
depend: [Waypoints]